### PR TITLE
Mock API solution

### PR DESCRIPTION
**Pull request by Polsander**
Found a solution to mock our API's. Took a bit of boilerplate, but now you should be able to mock your functions in the mock folder. 
**What this solves**
- Prevents failing test cases that require a server connection. We no longer need to be connected to our servers for our tests to pass. Hence, github actions will no longer be a problem.
- Allows us to mock functions in a way where we can provide our own request and responses. Could be potentially useful for front-end test cases, but I can't think of any crucial examples.

**Summary of changes**
We required 2 packages:
-  MSW which intercepts our api calls and takes over in our testing environment.
- cross-fetch, this prevents json response errors from our vanilla fetch function and makes it behave in a more browser stable way. This was needed to prevent our tests from failing as well.

Any api that needs to be mocked, please add it to the handlers array in `src/mock/handlers` file. You may follow my example.
Run your test via `npm run test` while you're not connected to skaffold dev to ensure it works.

### CODE REVIEW

**Comment by Polsander** [comment]
@ferncabrera Can you please test this via github actions and make sure everything passes as it should? Additionally check if you can run and pass all test cases while not running skaffold dev.

Lastly check and review the code and verify that you agree with my changes.

**Comment by Polsander** [comment]
@JosephFanous You can check as well and see how the code is set up incase you need to implement testing for your forgot password component.

**Review by ferncabrera — CHANGES_REQUESTED** [review]
@Polsander - Looks good! You can test it out yourself to see if the job is passing.

Goto the user_branch_acceptance_build_test workflow, (it has only Dockerfile commands and is the shortest workflow file. There you will see the commented out line that essentially runs the container with the unit tests:

image

AFAIK - The env var error is fixed since now we use env vars from vite set at build-time so should pass if you solved the issue! Just uncomment the line and push, both the user_branch_build_test and main_branch_acceptance_check jobs will run since you already made a PR but you're just looking for a passing user_branch_build_test since that one is running the tests.

**Comment by Polsander** [comment]
@ferncabrera Yes I can place the mock folder into our test folder. Good call.
I'll test the job itself after I make the change and will merge it by tomorrow. Thanks!

**Review by JosephFanous — DISMISSED** [review]

**Review by ferncabrera — APPROVED** [review]

**Pull request merged**
