### PR TITLE
Vite env vars; config refactor; prod env var fix

### PR DESCRIPTION
**Pull request by ferncabrera**
Possible fix for Vite env vars/config.

### CODE REVIEW

**Comment by ferncabrera** [comment]
Looks like all build checks are passing and I can confirm it builds/runs as expected on local with both skaffold profiles. Deploying to the cluster now.

**Comment by ferncabrera** [comment]
Looks like this did fix the issue. 

Please review the change that I made to the [tsconfig.node.json file](https://github.com/ferncabrera/open_ims/pull/54/files#diff-5001d83bff205213d81141b53faa7cda93a0ebc38991b494fb0516a3ca9ab21d) in this PR. 

When trying to build the client I would get weird "Unexpected char: you need additional plugins to handle imports of other types" errors. (Un-comment the line and try to run npm build).

I found the issue is because "If typeRoots is specified, only packages under typeRoots will be included." as per [the TS docs](If typeRoots is specified, only packages under typeRoots will be included.).

So then started looking into declaring global types since I didn't just want to comment this out but came across [this stackoverflow thread discouraging the use of global types](https://stackoverflow.com/questions/42233987/how-to-configure-custom-global-interfaces-d-ts-files-for-typescript). The first answer and questions are all you need to read.

Let me know what you think @Polsander.

**Comment by Polsander** [comment]
> Looks like this did fix the issue.
> 
> Please review the change that I made to the [tsconfig.node.json file](https://github.com/ferncabrera/open_ims/pull/54/files#diff-5001d83bff205213d81141b53faa7cda93a0ebc38991b494fb0516a3ca9ab21d) in this PR.
> 
> When trying to build the client I would get weird "Unexpected char: you need additional plugins to handle imports of other types" errors. (Un-comment the line and try to run npm build).
> 
> I found the issue is because "If typeRoots is specified, only packages under typeRoots will be included." as per [the TS docs](If typeRoots is specified, only packages under typeRoots will be included.).
> 
> So then started looking into declaring global types since I didn't just want to comment this out but came across [this stackoverflow thread discouraging the use of global types](https://stackoverflow.com/questions/42233987/how-to-configure-custom-global-interfaces-d-ts-files-for-typescript). The first answer and questions are all you need to read.
> 
> Let me know what you think @Polsander.
@ferncabrera 

I uncommented the line and my builds are still successful. I will message you directly about this to see and understand what the issue is with that.

As for global types, the OP in stackoverflow was using them wrong by trying to use import and export statements in the `.d.ts` files. Using them in this case contradicts their use as they are automatically exported as a global module, and using import/export in these files breaks them. (Think of those types being accessible by require("types") globally). So yes in a sense it is more "legacy", but I've been in projects where both `.ts` and `d.ts` type declarations are used. We are safe to use both and don't encounter any typescript or module building errors as long as we use the correct methodology of importing and exporting for them.

**Comment by Polsander** [comment]
As long as our `d.ts` files are in our source folder, typescript compiler will always find them and compile anyways. So we can leave it commented for now. We'd have to define typeroots if we have these declaration files outside of source. So for now, everything is good regardless. 😁

**Pull request merged**
