### PR TITLE
Github actions testing

### PR DESCRIPTION
**Pull request by ferncabrera**
Testing to see if the workflow runs on PR (or at all lol)

### CODE REVIEW

**Review by Polsander — APPROVED** [review]
Solve conflicts and I think we will be ok. Didn't know we define github actions in the root. Pretty cool to see how it's done.

**Comment by ferncabrera** [comment]
@Polsander LOL Yeah sorry about that - will make tests pass for now but I want to integrate the database ASAP since that is blocking us all atm (so the fix I merge in will mostly just be placeholder and not any real test). 

Mostly FYI for future self - I think in our case what would make the most sense is not so much standard unit-testing but rather integration testing, where we put up our whole app and test all components together. Setting up test envs for vite-react, express, and postgres would be overkill for now. We can do this integration testing with Skaffold Verify, but seems like not in the actual pipeline - we're going to need to setup our cluster in Digital Ocean so we can run our app there and do our integration testing, using namespaces in Kubernetes we should be able to actually launch a STAGING and PROD env in our cluster without issue although im still not 100% on the approach to take. 

Pinning this until DB is complete

**Comment by ferncabrera** [comment]
> Mostly FYI for future self - I think in our case what would make the most sense is not so much standard unit-testing but rather integration testing, where we put up our whole app and test all components together. Setting up test envs for vite-react, express, and postgres would be overkill for now. We can do this integration testing with Skaffold Verify, but seems like not in the actual pipeline - we're going to need to setup our cluster in Digital Ocean so we can run our app

Damn just spent some time reading on about this.... But:
Setting up PROD is priority #2, since this is a small project we're not going to have different envs (too expensive and while kubernetes namespaces sound tempting we can't risk a rouge process killing off our only prod instance..... maybe we pilot this during development and see how risky it seems. Opening a ticket for this.

Just read some more - looks like we **can** setup kubernetes for our GA pipeline and run a smoke-test on our app! Am going todo this now and integrate postgres as well.

**Comment by ferncabrera** [comment]
OK - Just implemented placeholder test that pushes your successfully build images to my dockerhub which you can view [here](https://hub.docker.com/repositories/fcabrera01) in the open-ims-client or open-ims-server image repos.

**Pull request merged**
